name: esp32 port

on:
  push:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - 'tools/**'
      - 'py/**'
      - 'extmod/**'
      - 'lib/**'
      - 'drivers/**'
      - 'ports/esp32/build-GENERIC_C3/**'
env:

  SSH_ACTIONS: true
  UPLOAD_WETRANSFER: true

  TZ: Asia/Shanghai

jobs:

  build_idf43:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: source tools/ci.sh && ci_esp32_idf43_setup

    - name: Start SSH via Ngrok
      if: ${{ failure() }}
      run: curl -sL https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
      env:
          # After sign up on the https://ngrok.com/
          # You can find this token here: https://dashboard.ngrok.com/get-started/setup
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          # This password you will use when authorizing via SSH
          USER_PASS: ${{ secrets.USER_PASS }}

    - name: Don't kill instace
      if: ${{ failure() }}
      run: sleep 1h # Prevent to killing instance after failure

    - name: Build
      run: source tools/ci.sh && ci_esp32_build

    - name: Download a Build Artifact
      uses: actions/upload-artifact@v2
      with:
          name: micropython
          path: ports/esp32/build-GENERIC_C3/*.bin
    - name: Upload firmware to WeTransfer
      id: wetransfer
      if: env.UPLOAD_WETRANSFER == 'true' && !cancelled()
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer wet /home/runner/work/micropython/micropython/ports/esp32/build-GENERIC_C3/*.bin
        echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
        echo "::set-output name=url::$(cat wetransfer.log | grep https | cut -f3 -d" ")"
